services:
  frontend:
    build:
      context: ./brainbolt-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - brainbolt-network
    restart: unless-stopped

  backend:
    build:
      context: ./brainbolt-be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-supersecretkey0987654321@!masterchief}
    depends_on:
      - db
      - redis
    networks:
      - brainbolt-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - brainbolt-network
    restart: unless-stopped

  redis:
    image: redis:latest
    networks:
      - brainbolt-network
    restart: unless-stopped

networks:
  brainbolt-network:
    driver: bridge

volumes:
  postgres_data:
